In [1]:
import torch 
import numpy as np
import dsntnn

C:\Users\Bxd\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
t1 = torch.randn(24).reshape([1,2,3,4])
t1

tensor([[[[ 0.2361, -0.8176, -0.9598, -0.3652],
          [-0.8845,  2.0987, -0.1237, -0.6479],
          [-0.3771, -1.0403,  0.3725, -1.2063]],

         [[ 0.1475,  1.2261,  0.3129,  0.3771],
          [-1.5386, -0.5114, -0.3449, -0.2635],
          [-0.1373,  0.4222, -0.3038,  0.0219]]]])

In [4]:
t2 = dsntnn.soft_argmax(t1)
t2

tensor([[[-1.1333, -0.2298],
         [ 0.8798, -1.3738]]])

In [6]:
t3 = dsntnn.flat_softmax(t1)
t3,t3.shape

(tensor([[[[0.0814, 0.0284, 0.0246, 0.0446],
           [0.0266, 0.5245, 0.0568, 0.0336],
           [0.0441, 0.0227, 0.0933, 0.0192]],
 
          [[0.0837, 0.2462, 0.0988, 0.1053],
           [0.0155, 0.0433, 0.0512, 0.0555],
           [0.0630, 0.1102, 0.0533, 0.0738]]]]),
 torch.Size([1, 2, 3, 4]))

In [7]:
t1.shape[2:]

torch.Size([3, 4])

In [10]:
from functools import reduce
from operator import mul
flat = t1.view(-1, reduce(mul, t1.size()[2:]))
flat = torch.nn.functional.softmax(flat, -1)
flat,flat.shape

(tensor([[0.0814, 0.0284, 0.0246, 0.0446, 0.0266, 0.5245, 0.0568, 0.0336, 0.0441,
          0.0227, 0.0933, 0.0192],
         [0.0837, 0.2462, 0.0988, 0.1053, 0.0155, 0.0433, 0.0512, 0.0555, 0.0630,
          0.1102, 0.0533, 0.0738]]),
 torch.Size([2, 12]))

In [ ]:
orig_size = t1.size()
flat = t1.view(-1, reduce(mul, orig_size[2:]))
flat = torch.nn.functional.softmax(flat, -1)
flat.view(*orig_size)